### ISSUE TITLE
Readme example error

### ISSUE THREAD

**Issue by felixleopoldo** [stagedtrees/stagedtrees#133]
Hi again,

I'm trying to run the example on the README.md but I get the error message below. Maybe I'm missing something.

```
> library("stagedtrees")
> 
> tree <- Titanic |> full() |> stages_bhc() |> stndnaming(uniq = TRUE)
```
_Error: unexpected '>' in "tree <- Titanic |>"_

**Comment by gherardovarando** [comment]
What version of R are you using?

**Comment by felixleopoldo** [comment]
R version 4.0.4 (2021-02-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS 14.0

**Comment by felixleopoldo** [comment]
Just updated to R 4.3, now it works, thanks.

**Comment by gherardovarando** [comment]
The example is using the pipe operator |> that was introduced recently.
Otherwise you can chain functions as usual and it will work also with older R versions.

**Comment by felixleopoldo** [comment]
Thanks, for the advice.
